# Generated by Django 5.0.2 on 2024-04-06 19:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('de_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_user',
            name='age',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
