# Generated by Django 4.2.5 on 2023-09-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('de_app', '0002_alter_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad_data',
            name='drawing',
            field=models.ImageField(upload_to='drawings/'),
        ),
    ]
