# Generated by Django 4.2.5 on 2023-09-23 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('de_app', '0004_emp_work_submission_time_alter_emp_work_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_work',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_entries', to='de_app.emp'),
        ),
    ]
