# Generated by Django 5.0.2 on 2024-04-06 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('de_app', '0005_alter_emp_work_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='emp_work',
            new_name='t_info',
        ),
        migrations.RenameModel(
            old_name='emp',
            new_name='t_user',
        ),
        migrations.DeleteModel(
            name='Ad_data',
        ),
    ]
