# Generated by Django 5.0.2 on 2024-04-06 17:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('de_app', '0006_rename_emp_work_t_info_rename_emp_t_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_info',
            old_name='component_name',
            new_name='income',
        ),
        migrations.RemoveField(
            model_name='t_info',
            name='quantity',
        ),
        migrations.AddField(
            model_name='t_info',
            name='income_goal',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_info',
            name='risk',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
