# Generated by Django 5.0.2 on 2024-04-06 17:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('de_app', '0007_rename_component_name_t_info_income_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_user',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
